version: "3.8"

services:
  db:
    image: mysql:8.0
    # platform linux/amd64: für die x86_64-Architektur (Apple Chip) aktivieren
    # platform: linux/amd64
    volumes:
      - ../data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: db_wp
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    # platform linux/amd64: für die x86_64-Architektur (Apple Chip) aktivieren
    # platform: linux/amd64
    ports:
      - "${HTTP_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: db_wp
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DEBUG: true
    working_dir: /var/www/html
    volumes:
      - ../data/wordpress:/var/www/html
      - ./php-custom.ini:/usr/local/etc/php/conf.d/php.ini
      - ../theme/dist:/var/www/html/wp-content/themes/${PROJECT_THEME_SLUG}

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_pw

  mailhog:
    image: mailhog/mailhog
    # platform linux/amd64: für die x86_64-Architektur (Apple Chip) aktivieren
    # platform: linux/amd64
    ports:
      - "8025:8025"
      - "1025:1025"